services:
  - type: web
    name: finance-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GOOGLE_CREDS_FILE
        value: credentials.json
      - key: WEBHOOK_URL
        value: https://finance-bot.onrender.com/$BOT_TOKEN
